# https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle
# https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle
gesdinet_jwt_refresh_token:
    # You can define Refresh Token TTL. Default value is 1 month.
    ttl: 2592000 
    # You can expand Refresh Token TTL on refresh. Default value is false.              
    # ttl_update: false
    # You can define your own UserProvider. By default we use our custom UserProvider.
    # user_provider: fos_user.user_provider.username_email
    # You can change user identity field. 
    # Make sure that your model user has getter for this field. Default value is username.    
    # user_identity_field: email
    user_identity_field: username
    # You can define Firewall name. Default value is api. 
    firewall: api/auth