# https://github.com/lexik/LexikJWTAuthenticationBundle
lexik_jwt_authentication:
    # private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    # public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        '%env(JWT_TOKENTTL)%'
    # key under which the user identity will be stored in the token payload
    # user_identity_field: email
    user_identity_field: username
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS512   
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization  
