# Important in files with the extension .yaml each indentation equals 4 spaces!!!!!

login:
    path: /login
    controller: App\Controller\ViewsController::index
signup:
    path: /signup
    controller: App\Controller\ViewsController::index
forget_password:
    path: /forget-password
    controller: App\Controller\ViewsController::index
index_page:
    path: /
    controller: App\Controller\ViewsController::index
home_page:
    path: /home
    controller: App\Controller\ViewsController::index
my_profile_page:
    path: /my-profile
    controller: App\Controller\ViewsController::index    