#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Important in files with extension.yaml each bleed equals 4 spaces!!!!
routing_distributed_v1:
    # loads routes from the given routing file stored in some bundle
    resource: '../src/Resources/config/routing.yml' 
    type: yaml