user_getData:
    path: /auth/get_data_user
    controller: App\Controller\UserController::getDataUser
user_updateData:
    path: /auth/update_data_user
    controller: App\Controller\UserController::updateDataUser    