App\Entity\ListContents:
    type: entity
    table: list_contents
    indexes:
        list_translations_sections_id:
            columns:
                - list_sections_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    manyToOne:
        listSections:
            targetEntity: ListSections
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                list_sections_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
