App\Entity\ListProductsSubcategory:
    type: entity
    table: list_products_subcategory
    indexes:
        user_id:
            columns:
                - user_id
        products_categories:
            columns:
                - products_categories_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        orderWeight:
            type: smallint
            nullable: false
            options:
                unsigned: false
            column: order_weight
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    manyToOne:
        productsCategories:
            targetEntity: ListProductsCategories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                products_categories_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
