App\Entity\ListLanguages:
    type: entity
    table: list_languages
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    lifecycleCallbacks: {  }
