App\Entity\ListAddressCity:
    type: entity
    table: list_address_city
    indexes:
        address_province:
            columns:
                - province
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cp:
            type: integer
            nullable: true
            options:
                unsigned: false
        city:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    manyToOne:
        province:
            targetEntity: ListAddressProvince
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                province:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
