App\Entity\Products:
    type: entity
    table: products
    indexes:
        provider_id:
            columns:
                - provider_id
        user_id:
            columns:
                - user_id
        products_subcategory:
            columns:
                - products_subcategory_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        reference:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        suitable:
            type: boolean
            nullable: false
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    manyToOne:
        productsSubcategory:
            targetEntity: ListProductsSubcategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                products_subcategory_id:
                    referencedColumnName: id
            orphanRemoval: false
        provider:
            targetEntity: Providers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                provider_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
