App\Entity\ProvidersProducts:
    type: entity
    table: providers_products
    indexes:
        products_id:
            columns:
                - product_id
        provider_id:
            columns:
                - provider_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        units:
            type: integer
            nullable: true
            options:
                unsigned: false
        surfaceArea:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: surface_area
        length:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        size:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        code:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        note:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    manyToOne:
        product:
            targetEntity: Products
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        provider:
            targetEntity: Providers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                provider_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
