App\Entity\RolesPermissions:
    type: entity
    table: roles_permissions
    indexes:
        permission:
            columns:
                - permission
        role:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:                
        value:
            type: boolean
            nullable: false
            column: value
        createdOn:
            type: datetime
            nullable: false
            column: created_on
    manyToOne:
        permission:
            targetEntity: ListPermissions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                permission:
                    referencedColumnName: id
            orphanRemoval: false
        role:
            targetEntity: ListRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: listPermissions
            joinColumns:
                role:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
